### ISSUE TITLE
[birthdays] list issue

### ISSUE THREAD

**Issue by coltoutram** [ZeLarpMaster/ZeCogsV3#10] opened 2018-07-02 14:41 UTC
Hey when I do [p]bday list, it shows a list of people with birthdays, about 50% of it doesnt actually show the correct user. It puts a <@!userID> and in the config file the ID's are all correct
![c9a84526-b760-4bfe-a54f-e0388398fafc](https://user-images.githubusercontent.com/25591704/42170439-cad63852-7e16-11e8-9749-f863cbf54abe.jpeg)

**Comment by ZeLarpMaster** [comment] 2018-07-02 16:21
This only happens if you don't have any servers in common with the user being tagged.

Which means those users most likely left your server.

**Comment by ZeLarpMaster** [comment] 2018-07-06 06:02
I tried to reproduce, but I couldn't find steps to make the "bug" happen again.

When the `[p]bday list` command is ran, the bot already removes any users which aren't visible by the bot anymore, so if those people weren't visible, they wouldn't be displayed there.

This makes me think your bot was in multiple servers and those users where in another server the bot is in, but you weren't in that other server so you couldn't see their names. My assumption might be wrong, but that's the best I can guess with what you've provided.

If it's indeed wrong, please provide exact steps to reproduce the error. If you can't find steps or what I've said solves the issue, please close this issue.

Thank you.

**Comment by mikeshardmind** [comment] 2018-10-24 00:52
`<@!{id}>` indicates a nickname in the mention, which would seem to indicate they are in the server with a nickname. This is more likely an issue with how discord parses embeds locally than something actually an issue on your end. (attempting to display a mention for a user that the client hasn't gotten an update for yet)

**Comment by ZeLarpMaster** [comment] 2019-01-09 03:50
Closing since there's nothing I can do about this. Resolving #15 might reduce the amount of times this happens.

**Closed by ZeLarpMaster** 2019-01-09 03:50 UTC
