### ISSUE TITLE
Reactrole error

### ISSUE THREAD

**Issue by Brandjuh** [ZeLarpMaster/ZeCogsV3#33] opened 2020-05-03 23:08 UTC
```
May 04 00:00:48 CuffbotV3 python[13848]:   return (yield from asyncio.shield(fut, loop=_loop))
May 04 00:05:15 CuffbotV3 python[13848]: Traceback (most recent call last):
May 04 00:05:15 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 119, in on_raw_reaction_remove
May 04 00:05:15 CuffbotV3 python[13848]:     await self.check_remove_role(payload)
May 04 00:05:15 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 422, in check_remove_role
May 04 00:05:15 CuffbotV3 python[13848]:     await self.bot.http.add_reaction(payload.message_id, payload.channel_id, payload.emoji._as_reaction())
May 04 00:05:15 CuffbotV3 python[13848]:   File "/root/redenv/lib/python3.8/site-packages/discord/http.py", line 223, in request
May 04 00:05:15 CuffbotV3 python[13848]:     raise NotFound(r, data)
May 04 00:05:15 CuffbotV3 python[13848]: discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel
May 04 00:05:29 CuffbotV3 python[13848]: Traceback (most recent call last):
May 04 00:05:29 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 119, in on_raw_reaction_remove
May 04 00:05:29 CuffbotV3 python[13848]:     await self.check_remove_role(payload)
May 04 00:05:29 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 422, in check_remove_role
May 04 00:05:29 CuffbotV3 python[13848]:     await self.bot.http.add_reaction(payload.message_id, payload.channel_id, payload.emoji._as_reaction())
May 04 00:05:29 CuffbotV3 python[13848]:   File "/root/redenv/lib/python3.8/site-packages/discord/http.py", line 223, in request
May 04 00:05:29 CuffbotV3 python[13848]:     raise NotFound(r, data)
May 04 00:05:29 CuffbotV3 python[13848]: discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel
May 04 00:05:30 CuffbotV3 python[13848]: Traceback (most recent call last):
May 04 00:05:30 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 119, in on_raw_reaction_remove
May 04 00:05:30 CuffbotV3 python[13848]:     await self.check_remove_role(payload)
May 04 00:05:30 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 422, in check_remove_role
May 04 00:05:30 CuffbotV3 python[13848]:     await self.bot.http.add_reaction(payload.message_id, payload.channel_id, payload.emoji._as_reaction())
May 04 00:05:30 CuffbotV3 python[13848]:   File "/root/redenv/lib/python3.8/site-packages/discord/http.py", line 223, in request
May 04 00:05:30 CuffbotV3 python[13848]:     raise NotFound(r, data)
May 04 00:05:30 CuffbotV3 python[13848]: discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel
May 04 00:05:30 CuffbotV3 python[13848]: Traceback (most recent call last):
May 04 00:05:30 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 119, in on_raw_reaction_remove
May 04 00:05:30 CuffbotV3 python[13848]:     await self.check_remove_role(payload)
May 04 00:05:30 CuffbotV3 python[13848]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/react_roles/react_roles.py", line 422, in check_remove_role
May 04 00:05:30 CuffbotV3 python[13848]:     await self.bot.http.add_reaction(payload.message_id, payload.channel_id, payload.emoji._as_reaction())
May 04 00:05:30 CuffbotV3 python[13848]:   File "/root/redenv/lib/python3.8/site-packages/discord/http.py", line 223, in request
May 04 00:05:30 CuffbotV3 python[13848]:     raise NotFound(r, data)
May 04 00:05:30 CuffbotV3 python[13848]: discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel
```

**Comment by aikaterna** [comment] 2020-09-17 22:22
Seems like this occurs when the bot is removing reacts on other commands like audio's [p]now after a timeout.

**Comment by ZeLarpMaster** [comment] 2020-09-17 23:32
That would make sense, if you're able to reproduce, I've made a change which might solve the issue. Do tell me if it's fixed after updating to the latest version.

**Comment by aikaterna** [comment] 2020-10-02 17:57
I haven't seen this error since I've updated.

**Comment by ZeLarpMaster** [comment] 2020-10-09 03:51
I'll close this then, feel free to reopen or make a new one about it if it happens again.

**Closed by ZeLarpMaster** 2020-10-09 03:51 UTC
